### ISSUE TITLE
Update currying section in Fun with Functions post

### ISSUE THREAD

**Issue by samirGuerdah** [AliSoftware/alisoftware.github.io#4]
Hello,

Perhaps an update of the section "**Currying**" in the **Fun with Functions** post ?. The curried syntaxe will be removed in Swift. 

https://github.com/apple/swift-evolution/blob/master/proposals/0002-remove-currying.md
[](https://github.com/apple/swift-evolution/blob/master/proposals/0002-remove-currying.md)

**Comment by AliSoftware** [comment]
:ok_hand:
